# Greek Math Reader for NVDA
# Copyright (C) 2026 Christos Bouronikos
# This file is covered by the GNU General Public License version 3 or later.
# See the file COPYING.txt for more details.
# SPDX-License-Identifier: GPL-3.0-or-later
# NVDA Greek Math (Greek Math Reader) by Bouronikos Christos (cbouronikos@uth.gr)
# Additional attribution terms under GPL-3.0 section 7 apply - see LICENSE.md.
# Project contact: Bouronikos Christos <chrisbouronikos@gmail.com>
# GitHub: https://github.com/ChristosBouronikos
# Author / maintainer: Christos Bouronikos  ·  chrisbouronikos@gmail.com
# Greek Math Reader is free, open-source software. If it helps make
# mathematics more accessible for you, please consider a kind, optional
# donation — it directly supports continued development. Thank you!
#   PayPal: https://paypal.me/christosbouronikos

"""The catalogue of downloadable speech runtimes and voice models.

``catalogue.json`` is generated by ``tools/refresh_voice_catalogue.py`` and every
entry carries a SHA-256 that was observed by actually reading the bytes. Nothing
in this package will install a download whose digest is missing, so a typo in the
catalogue fails closed rather than running unverified code.

No NVDA imports: the catalogue is plain data and is unit-tested directly.
"""

import json
import os

from . import platforms

CATALOGUE_FILENAME = "catalogue.json"

#: Digests are 64 hexadecimal characters. Anything else is treated as unpinned.
_SHA256_LENGTH = 64


class CatalogueError(Exception):
	"""The catalogue file is missing, malformed or not pinned."""


class Download:
	"""One verifiable file to fetch."""

	def __init__(self, filename, url, size, sha256):
		self.filename = filename
		self.url = url
		self.size = int(size)
		self.sha256 = (sha256 or "").lower()

	@property
	def isPinned(self):
		return len(self.sha256) == _SHA256_LENGTH and all(
			character in "0123456789abcdef" for character in self.sha256
		)

	@classmethod
	def fromDict(cls, data):
		return cls(data["filename"], data["url"], data["size"], data.get("sha256"))


class Voice:
	"""One downloadable voice model."""

	def __init__(self, data):
		self.id = data["id"]
		self.label = data["label"]
		self.family = data["family"]
		self.languages = tuple(data.get("languages", ()))
		self.notes = data.get("notes", "")
		self.licenseId = data.get("licenseId", "")
		self.licenseName = data.get("licenseName", "")
		self.licenseUrl = data.get("licenseUrl", "")
		#: True when the licence imposes terms on downstream recipients, which
		#: means the add-on may not redistribute it and the user must agree.
		self.requiresLicenseAcceptance = bool(data.get("licenseAcceptance", False))
		self.recommended = bool(data.get("recommended", False))
		self.download = Download(
			os.path.basename(data["archive"]),
			data["url"],
			data["size"],
			data.get("sha256"),
		)

	@property
	def sizeMegabytes(self):
		return self.download.size / 1000000.0

	def speaks(self, language):
		"""Whether this voice covers ``language`` (an ISO 639-1 code)."""
		code = (language or "").split("_")[0].split("-")[0].lower()
		return code in self.languages


class Catalogue:
	"""Parsed ``catalogue.json``."""

	def __init__(self, data):
		self._runtime = data.get("runtime", {})
		self.runtimeVersion = self._runtime.get("version", "")
		self.runtimeLicense = self._runtime.get("license", "")
		self.voices = [Voice(entry) for entry in data.get("voices", [])]

	def voice(self, voiceId):
		for voice in self.voices:
			if voice.id == voiceId:
				return voice
		return None

	def voicesForLanguage(self, language):
		"""Voices covering ``language``, recommended ones first."""
		matches = [voice for voice in self.voices if voice.speaks(language)]
		return sorted(matches, key=lambda voice: (not voice.recommended, voice.label))

	def runtimeDownloads(self, versionInfo=None, platformName=None):
		"""Return the wheels needed by the running interpreter.

		Two are required: the CPython-ABI bindings and the architecture's native
		core library. Returns an empty list when this platform has no build.
		"""
		bindingKey = platforms.platformKey(versionInfo, platformName)
		architecture = platforms.platformTag(platformName)
		binding = self._runtime.get("bindings", {}).get(bindingKey)
		core = self._runtime.get("core", {}).get(architecture)
		if not binding or not core:
			return []
		return [Download.fromDict(binding), Download.fromDict(core)]

	def validate(self):
		"""Raise ``CatalogueError`` unless every entry is digest-pinned."""
		unpinned = [voice.id for voice in self.voices if not voice.download.isPinned]
		if unpinned:
			raise CatalogueError(
				"voice entries are not digest-pinned: " + ", ".join(sorted(unpinned))
			)
		return True


def loadCatalogue(path=None):
	"""Read and parse the catalogue shipped beside this module."""
	target = path or os.path.join(os.path.dirname(os.path.abspath(__file__)), CATALOGUE_FILENAME)
	try:
		with open(target, "r", encoding="utf-8") as handle:
			data = json.load(handle)
	except (OSError, ValueError) as error:
		raise CatalogueError("could not read {0}: {1}".format(target, error))
	return Catalogue(data)
