#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# NVDA Greek Math (Greek Math Reader) by Bouronikos Christos (cbouronikos@uth.gr)
# Additional attribution terms under GPL-3.0 section 7 apply - see LICENSE.md.
"""Export reviewable MathCAT Greek assets from the add-on's canonical data."""

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENGINE_ROOT = PROJECT_ROOT / "addon" / "globalPlugins" / "greekMathReader"
sys.path.insert(0, str(ENGINE_ROOT))

from engine import ReadingConfig, get_last_engine_diagnostics, speak_mathml, tokens_to_text  # noqa: E402
from engine.terminology_el import (  # noqa: E402
	TERMINOLOGY_VERSION,
	TERMS,
	SEMANTIC_MODULES,
	mathcat_intent_record,
	terminology_record,
)


OUTPUT_ROOT = PROJECT_ROOT / "mathcat-el" / "generated"


def _yaml_string(value):
	return json.dumps(value, ensure_ascii=False)


def render_intent_mappings():
	lines = [
		"# Generated by tools/export_mathcat_el.py; do not edit by hand.",
		f"# Greek Math Reader terminology registry: {TERMINOLOGY_VERSION}",
		"# Merge these candidates into Rules/Languages/el/definitions.yaml after review.",
		"- IntentMappings: {",
	]
	for concept in sorted(TERMS):
		record = mathcat_intent_record(concept)
		mapping = f"{record['fixity']}={record['head']}"
		lines.append(
			f"    {_yaml_string(record['name'])}: {_yaml_string(mapping)},"
			f" # {record['reviewStatus']}"
		)
	lines.append("  }")
	return "\n".join(lines) + "\n"


def render_registry():
	payload = {
		"schemaVersion": 1,
		"terminologyVersion": TERMINOLOGY_VERSION,
		"language": "el",
		"modules": SEMANTIC_MODULES,
		"entries": [terminology_record(concept) for concept in sorted(TERMS)],
	}
	return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _golden_cases():
	cases = []
	corpus_root = PROJECT_ROOT / "tests" / "corpus"
	for path in sorted(corpus_root.glob("*.mathml")):
		mathml = path.read_text(encoding="utf-8").strip()
		speech = tokens_to_text(speak_mathml(mathml, ReadingConfig()))
		cases.append({
			"id": path.stem,
			"mathml": mathml,
			"standardSpeech": speech,
			"diagnostics": get_last_engine_diagnostics(),
		})
	return cases


def render_golden_corpus():
	payload = {
		"schemaVersion": 1,
		"terminologyVersion": TERMINOLOGY_VERSION,
		"language": "el",
		"speechStyle": "Standard",
		"cases": _golden_cases(),
	}
	return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def generated_outputs():
	return {
		OUTPUT_ROOT / "semantic-intents.yaml": render_intent_mappings(),
		OUTPUT_ROOT / "terminology-registry.json": render_registry(),
		OUTPUT_ROOT / "golden-corpus.json": render_golden_corpus(),
	}


def write_outputs(check=False):
	stale = []
	for path, content in generated_outputs().items():
		if check:
			if not path.exists() or path.read_text(encoding="utf-8") != content:
				stale.append(path)
			continue
		path.parent.mkdir(parents=True, exist_ok=True)
		path.write_text(content, encoding="utf-8")
	return stale


def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("--check", action="store_true", help="fail if generated assets are stale")
	args = parser.parse_args()
	stale = write_outputs(check=args.check)
	if stale:
		for path in stale:
			print(f"stale: {path.relative_to(PROJECT_ROOT)}", file=sys.stderr)
		return 1
	if not args.check:
		print(f"generated {len(generated_outputs())} MathCAT assets in {OUTPUT_ROOT}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
